version: '2'
services:
  app:
    image: node:7
    ports:
      - "3000:3000"
    volumes:
      - .:/mesosir
    entrypoint:
      - /mesosir/launch.sh
    environment:
      - GIT_REPO=https://github.com/agate/mesosir.git
      - MESOS_HOST=${MESOS_HOST}
      - MESOS_PORT=${MESOS_PORT}
      - MESOS_SLAVE_PORT=${MESOS_PORT}
